# Generated by Django 4.2.5 on 2023-09-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0003_empevent_employeeemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEmailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_email', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('event_message', models.CharField(max_length=300)),
                ('email_status', models.CharField(max_length=10)),
                ('email_error', models.CharField(max_length=300)),
            ],
        ),
    ]
