# Generated by Django 4.2.5 on 2023-09-11 02:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0004_eventemailstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('event_email_log', models.CharField(max_length=100)),
                ('execution_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='eventemailstatus',
            name='execution_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
