# Generated by Django 4.2.5 on 2023-09-11 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0005_eventlog_eventemailstatus_execution_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('system_log', models.CharField(max_length=100)),
            ],
        ),
    ]
