# Generated by Django 4.2.5 on 2023-09-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0006_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='system_status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
